source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AVReachability_Example', :exclusive => true do
  pod "AVReachability", :path => "../"
end

target 'AVReachability_Tests', :exclusive => true do
  pod "AVReachability", :path => "../"

  
end
